services:
  mongodb:
    image: mongo:7.0.4
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  nestjs:
    build:
      context: ./nest-backend
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_DATABASE: grants_db
      MONGODB_URI: mongodb://mongodb:27017/grants_db

  reactjs:
    build:
      context: ./reactjs-frontend
      dockerfile: Dockerfile
    container_name: reactjs
    ports:
      - '3000:3000'
    depends_on:
      - nestjs

volumes:
  mongo-data:
